name: CLIENTE-CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Node
        uses: actions/setup-node@v3
        with:
          node-version: '22' 

      - name: Instalar dependencias
        run: npm ci

      - name: Ejecutar pruebas
        run: npm run test 

      - name: Build de Angular 
        run: npm run build 
